In [1]:
import numpy as np

## Create ndarrays

- the easist way to create an array is using the `array` function, it accepts any sequence-like object

In [4]:
data1 = [1, 2, 3, 4, 5]
arr1 = np.array(data1)
arr1.ndim

1

In [5]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2.ndim

2

In [7]:
arr2.shape

(2, 4)

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

## Basic Indexing and Slicing

In [13]:
arr = np.array([1, 2, 3, 4])

In [14]:
arr[1: 3]

array([2, 3])

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [16]:
arr[0][2]

3

In [17]:
arr[1][1]

5

## Mathematical and Statistical Methods

Aggregation functions include `sum`, `mean` and standard deviation `std`

In [20]:
arr = np.random.randn(5, 4)

print(arr.mean())
print(np.mean(arr))

-0.26633793655347215
-0.26633793655347215


In [21]:
arr.sum()

-5.326758731069443

## Methods for Boolean Arrays

In [22]:
bools = np.array([True, False, True, False])

In [23]:
bools.any()

True

In [24]:
bools.all()

False

### Sorting

In [25]:
arr = np.random.randn(8)

In [26]:
arr

array([ 2.48305043e-01,  1.88731005e+00,  1.04982733e+00,  5.44348111e-01,
        1.85079753e-03, -1.54803021e+00, -1.14287603e+00, -7.37341961e-02])

In [28]:
arr.sort()

print(arr)

[-1.54803021e+00 -1.14287603e+00 -7.37341961e-02  1.85079753e-03
  2.48305043e-01  5.44348111e-01  1.04982733e+00  1.88731005e+00]
